# Generated by Django 5.2.7 on 2026-01-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userprofile_email_userprofile_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadblockreport",
            name="nearby_place",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
