# Generated by Django 5.2.7 on 2026-01-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_roadblockreport_nearby_place"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roadblockreport",
            options={
                "permissions": [
                    ("can_view_moderation", "Can view moderation dashboard"),
                    ("can_verify_report", "Can verify roadblock reports"),
                    ("can_resolve_report", "Can resolve roadblock reports"),
                ]
            },
        ),
    ]
